version: '3.7' 

services: 

  client: 
    container_name: game_client 
    build: 
      context: . 
      dockerfile: Dockerfile 
    ports:
      - 3000:3000
    environment: 
      - CHOKIDAR_USEPOLLING=true